name: infrastructure_shared
description: Shared infrastructure services and abstractions for WHPH.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.5.3
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  application:
    path: ../../core/application
  domain:
    path: ../../core/domain
  acore:
    path: ../../../packages/acore-flutter

  # Shared infrastructure dependencies
  window_manager: ^0.4.3
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: false
