name: presentation_api
description: WebSocket API server for sync functionality in WHPH.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.5.3
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../../core/domain
  application:
    path: ../../core/application
  dart_json_mapper: ^2.2.16
  mediatr: ^0.2.1
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: false
